### ISSUE TITLE
I18N问题及其他显示BUG

### ISSUE THREAD

**Issue by TikaFlow** [auroral-ui/hexo-plugin-aurora#19]
# 环境
- Hexo版本：7.0.0-rc2
- 插件版本：hexo-plugin-aurora v1.8.3 & hexo-theme-aurora v2.5.2
- 浏览器：Chrome 116.0.5845.188
- dependencies：
```
    "hexo": "^7.0.0-rc2",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-plugin-aurora": "^1.8.3",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.6",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-aurora": "^2.5.2"
```
# 遇到问题
## 1、搜索按钮无法点击
页面为滑动时（未展示多语言按钮）搜索按钮无法点击。经测试，在以下状态下可以点击：
- 页面往下滑，此时搜索按钮右侧出现回到顶部的按钮，搜索按钮亦可用；
- 展示多语言按钮，此时搜索按钮可用。
猜测：当右上角少于3个按钮时，搜索按钮无法点击
## 2、多语言问题
设置语言为`zh-CN`且多语言为`false`时，菜单标题仍然显示为英文（不是缓存问题）
> 此问题未能稳定复现，偶尔重启网站后未出现

**且自定义菜单（如留言板）不配置I18N则无法显示**
在英文情况下，菜单显示为全大写，希望能与填写的一致
## 3、图片显示问题
社交链接的图标（如`gitee`/`github`），无法显示；配置如下：
```yml
github:
      icon: '/img/github.png'
      link: 'https://github.com/TikaFlow'
```
## 4、代码高亮问题
配置如下：
```yml
shiki:
  enable: true
  theme: 'monokai'
```
效果：可显示行号，但无高亮
# 以上问题在旧版（大约hexov6.3&plugV1.7&themeV2.0）均未发生
**如因版本更新导致配置方式变更，请说明**
**如plugin与theme有版本搭配问题存在，请列出各版本搭配**
十分期待并感谢您的回复！
