### ISSUE TITLE
Waline错位

### ISSUE THREAD

**Issue by MATRIX06060** [auroral-ui/hexo-plugin-aurora#3]
按照帮助文档给出的Waline操作会出现如下情况
![图片](https://github.com/auroral-ui/hexo-theme-aurora/assets/119382805/2db91f4f-24a0-426c-b7ab-f2ed8b1aae21)

**Comment by bennyxguo** [comment]
在 `__aurora.config.yaml` 中加一下面这些配置：

```yaml
# Twikoo comment plugin
# see https://twikoo.js.org/quick-start.html
twikoo:
  enable: false
  recentComment: true
  envId: xxxxxxxxxxxxxxx # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  # region: ap-guangzhou # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
  lang: 'en' # 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js

# Waline comment plugin
# see https://waline.js.org/guide/get-started/
waline:
  enable: false
  recentComment: true
  reaction: false
  login: 'disable'
  meta: ['nick', 'mail']
  requiredMeta: ['nick', 'mail']
  commentSorting: 'latest'
  wordLimit: 0,
  imageUploader: false,
  serverURL: '' # 填写服务端地址
```
